---
# Ansible file supporting the build of a SOF-ELK(R) standalone system
# (C)2025 Lewes Technology Consulting, LLC

base_apt_packages:
  - at
  - bc
  - bind9-dnsutils
  - btop
  - bzip2
  - chrony
  - cifs-utils
  - console-data
  - cron
  - curl
  - eject
  - exfat-fuse
  - file
  - firewalld
  - gcc
  - geoip-bin
  - geoipupdate
  - git
  - htop
  - jq
  - locate
  - logrotate
  - lsof
  - net-tools
  - nfdump
  - p7zip
  - psmisc
  - python3-dev
  - python3-elasticsearch
  - python3-pip
  - rsync
  - screen
  - tcpdump
  - tree
  - unzip
  - vim
  - virt-what
  - whois

vmware_apt_packages:
  - open-vm-tools

revision_string: "<%REVNO%>"

debian_sources:
  - repo: "deb http://deb.debian.org/debian/ trixie main contrib non-free non-free-firmware"
    state: present
    filename: "debian-trixie"
  - repo: "deb-src http://deb.debian.org/debian/ trixie main contrib non-free non-free-firmware"
    state: present
    filename: "debian-trixie"
  - repo: "deb http://deb.debian.org/debian/ trixie-updates main contrib non-free non-free-firmware"
    state: present
    filename: "debian-trixie-updates"
  - repo: "deb-src http://deb.debian.org/debian/ trixie-updates main contrib non-free non-free-firmware"
    state: present
    filename: "debian-trixie-updates"
