---
# Ansible file supporting the build of a SOF-ELK(R) standalone system
# (C)2024 Lewes Technology Consulting, LLC

base_apt_packages:
  - at
  - bc
  - bind9-dnsutils
  - btop
  - bzip2
  - cifs-utils
  - cron
  - eject
  - exfat-fuse
  - file
  - firewalld
  - gcc
  - geoip-bin
  - geoipupdate
  - git
  - htop
  - jq
  - locate
  - logrotate
  - lsof
  - net-tools
  - nfdump
  - p7zip
  - psmisc
  - python3-dev
  - python3-elasticsearch
  - python3-pip
  - rsync
  - screen
  - tcpdump
  - tree
  - unzip
  - vim
  - whois

vmware_apt_packages:
  - open-vm-tools

revision_string: "<%REVNO%>"
