---
base_yum_packages:
  - GeoIP
  - geoipupdate
  - bc
  - bind-utils
  - bzip2
  - cifs-utils
  - deltarpm
  - exfat-utils
  - fuse-exfat
  - gcc
  - git
  - htop
  - htop
  - java-1.8.0
  - java-1.8.0-devel
  - jq
  - lsof
  - mlocate
  - net-tools
  - nfdump
  - open-vm-tools
  - p7zip
  - psmisc
  - python-devel
  - python-pip
  - python-requests
  - python-six
  - python36
  - python36-pip
  - python36-six
  - tcpdump
  - unzip
  - vim
  - wget
  - whois
  - yum-plugin-post-transaction-actions
