---
- name: Install domain-stats pip dependencies
  pip:
    name: python-whois
    executable: pip3
    state: present
  tags: sof-elk_domainstats

- name: Install domain-stats
  pip:
    name: domain-stats
    executable: pip3
    state: present
  tags: sof-elk_domainstats

- name: Install domain-stats configuration
  copy:
    src: '{{ item }}'
    dest: /usr/local/share/domain-stats/
    owner: root
    group: root
    mode: 0640
  with_items:
    - 'domain-stats.yaml'
    - 'gunicorn_config.py'
  tags: sof-elk_domainstats

- name: Copy freq table to operational location
  copy:
    remote_src: yes
    src: /usr/local/lib/python3.6/site-packages/domain_stats/data/freqtable2018.freq
    dest: /usr/local/share/domain-stats/
  tags: sof-elk_domainstats

- name: Install Top 1M records
  shell: domain-stats-utils -i /usr/local/lib/python3.6/site-packages/domain_stats/data/top1m.import -nx /usr/local/share/domain-stats/

- name: Enable domain-stats service
  systemd:
    name: /usr/local/sof-elk/lib/systemd/domain-stats.service
    enabled: yes
  tags: sof-elk_domainstats

- name: Start domain-stats service
  systemd:
    name: domain-stats
    state: started
  tags: sof-elk_domainstats
