---
- name: Check if EPEL repo is already configured
  stat:
    path: '{{ epel_repofile_path }}'
  register: epel_repofile_result

- name: Install EPEL repo
  yum:
    name: '{{ epel_repo_url }}'
    state: present
  when: not epel_repofile_result.stat.exists
  register: yum_repo_installed

- name: Import EPEL GPG key
  rpm_key:
    key: '{{ epel_repo_gpg_key_url }}'
    state: present
  when: not epel_repofile_result.stat.exists
