---
- name: Install Logstash
  yum:
    name: logstash
    state: present
  tags: sof-elk_logstash

- name: Install Logstash Plugins
  logstash_plugin:
    name: '{{ item }}'
    state: present
  with_items:
    - logstash-input-relp
# VERSION CONFLICT - IGNORING FOR NOW
#    - logstash-filter-tld
    - logstash-filter-rest
    - logstash-filter-json_encode
    - logstash-filter-cidr
  tags: sof-elk_logstash

- name: Set Logstash JVM options
  lineinfile:
    dest: '/etc/logstash/jvm.options'
    regexp: '^-Xms'
    line: '-Xms750m'
  tags: sof-elk_logstash

- name: Get list of all configfiles
  find:
    paths: '/usr/local/sof-elk/configfiles/'
    file_type: file
  register: configfile_results
  tags: sof-elk_logstash

- name: Set symlinks for pipeline configuration
  file:
    src: '/usr/local/sof-elk/configfiles/{{ item.path | basename }}'
    dest: '/etc/logstash/conf.d/{{ item.path | basename }}'
    state: link
  with_items:
    - '{{ configfile_results.files }}'
  tags: sof-elk_logstash

- name: Start and Enable Logstash service
  systemd:
    name: logstash
    enabled: yes
    state: started
  tags: sof-elk_logstash
